FROM python:3.9
WORKDIR /app
COPY app.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000
#CMD ["python", "app.py"]

CMD ["flask", "run", "--host=0.0.0.0", "--port", "5000"]
